import type { PrimaryStats } from "../progression/stats";

/**
 * Enemy definitions for Korriban.
 * Source: Master Design Bible §6 "Enemigos" + §7 "Jefes".
 */

export interface EnemyTemplate {
  id: string;
  name: string;
  description: string;
  level: number;
  category: "minion" | "elite" | "boss";
  /** Base primary stats (scaled by level). */
  primary: PrimaryStats;
  /** Base HP (before endurance scaling). */
  baseHp: number;
  /** Base Force points (0 for beasts). */
  baseFp: number;
  armor: number;
  resistances: Partial<Record<string, number>>;
  /** Skills this enemy can use. */
  skillIds: string[];
  /** Loot table ID. */
  lootTableId: string;
  /** XP reward. */
  xpReward: number;
  /** Credit reward range [min, max]. */
  creditReward: [number, number];
  /** AI behavior tag. */
  aiBehavior: "aggressive" | "defensive" | "random" | "smart";
}

export const KORRIBAN_ENEMIES: EnemyTemplate[] = [
  // ─── Minions ─────────────────────────────────────────────────────────
  {
    id: "sith_acolyte",
    name: "Acólito Sith",
    description: "Un compañero de estudios que compite por el favor de tu maestro. Peligroso y desesperado.",
    level: 1,
    category: "minion",
    primary: { strength: 5, agility: 4, endurance: 4, force: 3, influence: 2, corruption: 1 },
    baseHp: 80,
    baseFp: 20,
    armor: 15,
    resistances: {},
    skillIds: ["enemy_slash", "enemy_force_push"],
    lootTableId: "loot_acolyte",
    xpReward: 25,
    creditReward: [5, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "klor_slug",
    name: "Babosa k'lor",
    description: "Un insectoide excavador venenoso. Las tumbas de Korriban están infestadas de ellos.",
    level: 1,
    category: "minion",
    primary: { strength: 6, agility: 3, endurance: 5, force: 0, influence: 0, corruption: 0 },
    baseHp: 60,
    baseFp: 0,
    armor: 20,
    resistances: { poison: 0.5 },
    skillIds: ["enemy_bite", "enemy_poison_spit"],
    lootTableId: "loot_beast",
    xpReward: 15,
    creditReward: [0, 5],
    aiBehavior: "aggressive",
  },
  {
    id: "tuk_ata",
    name: "Tuk'ata",
    description: "Sabueso sith sensible a la Fuerza. Cazadores implacables que recorren el Valle de los Lores Oscuros.",
    level: 2,
    category: "minion",
    primary: { strength: 7, agility: 6, endurance: 5, force: 2, influence: 0, corruption: 0 },
    baseHp: 90,
    baseFp: 0,
    armor: 25,
    resistances: { force: 0.2 },
    skillIds: ["enemy_bite", "enemy_claw_swipe", "enemy_howl"],
    lootTableId: "loot_beast",
    xpReward: 30,
    creditReward: [0, 8],
    aiBehavior: "aggressive",
  },
  {
    id: "shyrack",
    name: "Shyrack",
    description: "Moradores de cuevas con aspecto de murciélago. Débiles en solitario, mortíferos en enjambre.",
    level: 1,
    category: "minion",
    primary: { strength: 3, agility: 7, endurance: 2, force: 0, influence: 0, corruption: 0 },
    baseHp: 35,
    baseFp: 0,
    armor: 5,
    resistances: {},
    skillIds: ["enemy_bite"],
    lootTableId: "loot_beast",
    xpReward: 10,
    creditReward: [0, 2],
    aiBehavior: "random",
  },
  {
    id: "tomb_droid",
    name: "Droide Guardián de la Tumba",
    description: "Un antiguo droide de seguridad aún funcional tras milenios. Fuertemente blindado.",
    level: 3,
    category: "minion",
    primary: { strength: 6, agility: 2, endurance: 8, force: 0, influence: 0, corruption: 0 },
    baseHp: 120,
    baseFp: 0,
    armor: 60,
    resistances: { mental: 1.0, poison: 1.0, force: 0.5 },
    skillIds: ["enemy_blaster", "enemy_shock"],
    lootTableId: "loot_droid",
    xpReward: 35,
    creditReward: [10, 25],
    aiBehavior: "defensive",
  },

  // ─── Elites ──────────────────────────────────────────────────────────
  {
    id: "sith_pureblood",
    name: "Guerrero Sith de Sangre Pura",
    description: "Un Sith de sangre pura. Más fuerte en la Fuerza, desdeñoso con las especies inferiores.",
    level: 4,
    category: "elite",
    primary: { strength: 8, agility: 5, endurance: 7, force: 6, influence: 5, corruption: 4 },
    baseHp: 200,
    baseFp: 60,
    armor: 50,
    resistances: { force: 0.15 },
    skillIds: ["enemy_slash", "enemy_force_choke", "enemy_rage"],
    lootTableId: "loot_elite_sith",
    xpReward: 80,
    creditReward: [30, 60],
    aiBehavior: "smart",
  },
  {
    id: "tomb_wraith",
    name: "Espectro de la Tumba",
    description: "Un vestigio espectral de un antiguo Lord Sith. Aparece y desaparece de la existencia.",
    level: 5,
    category: "elite",
    primary: { strength: 4, agility: 8, endurance: 4, force: 9, influence: 3, corruption: 7 },
    baseHp: 150,
    baseFp: 100,
    armor: 10,
    resistances: { physical: 0.5, energy: 0.3, force: -0.2 },
    skillIds: ["enemy_force_drain", "enemy_fear_aura", "enemy_shadow_strike"],
    lootTableId: "loot_wraith",
    xpReward: 100,
    creditReward: [0, 20],
    aiBehavior: "smart",
  },

  // ─── Bosses ──────────────────────────────────────────────────────────
  {
    id: "tomb_guardian_boss",
    name: "Guardián de la Tumba",
    description: "Un antiguo constructo de guerra sith reactivado por tu intrusión. Protege el sanctasanctórum interior.",
    level: 5,
    category: "boss",
    primary: { strength: 10, agility: 3, endurance: 12, force: 4, influence: 0, corruption: 3 },
    baseHp: 500,
    baseFp: 40,
    armor: 80,
    resistances: { physical: 0.15, mental: 0.8, poison: 1.0 },
    skillIds: ["enemy_slam", "enemy_shield_bash", "enemy_ancient_beam", "enemy_enrage"],
    lootTableId: "loot_boss_guardian",
    xpReward: 250,
    creditReward: [80, 150],
    aiBehavior: "smart",
  },
  {
    id: "tomb_beast",
    name: "Bestia de la Tumba",
    description: "Una criatura que ha vivido en las tumbas oscuras durante siglos, alimentándose de carroña y de los ecos de la energía del lado oscuro. Brutales ataques de sangrado.",
    level: 4,
    category: "elite",
    primary: { strength: 10, agility: 7, endurance: 9, force: 0, influence: 0, corruption: 3 },
    baseHp: 220,
    baseFp: 0,
    armor: 25,
    resistances: { poison: 0.4 },
    skillIds: ["enemy_claw_swipe", "enemy_bleed_slash", "enemy_charge"],
    lootTableId: "loot_beast",
    xpReward: 90,
    creditReward: [5, 20],
    aiBehavior: "aggressive",
  },
  {
    id: "darth_voren",
    name: "Darth Voren",
    description: "Tu primer maestro en la Academia. Cruel, poderoso y convencido de que eres prescindible. Te aguarda un duelo ritual.",
    level: 7,
    category: "boss",
    primary: { strength: 9, agility: 7, endurance: 8, force: 10, influence: 8, corruption: 6 },
    baseHp: 800,
    baseFp: 150,
    armor: 65,
    resistances: { force: 0.25, mental: 0.4 },
    skillIds: [
      "enemy_saber_combo",
      "enemy_force_lightning",
      "enemy_force_choke",
      "enemy_dark_heal",
      "enemy_rage",
    ],
    lootTableId: "loot_boss_voren",
    xpReward: 500,
    creditReward: [200, 400],
    aiBehavior: "smart",
  },
];

// ─── Korriban expansion — quest bosses & new fauna ─────────────────────

export const KORRIBAN_EXPANSION_ENEMIES: EnemyTemplate[] = [
  {
    id: "daryth_rival",
    name: "Daryth",
    description: "Tu acólito rival. Su crueldad solo la iguala su ambición — y hoy, uno de los dos sale de la arena en brazos.",
    level: 3,
    category: "elite",
    primary: { strength: 7, agility: 6, endurance: 5, force: 4, influence: 3, corruption: 2 },
    baseHp: 160,
    baseFp: 40,
    armor: 30,
    resistances: {},
    skillIds: ["enemy_slash", "enemy_saber_combo", "enemy_force_push", "enemy_rage"],
    lootTableId: "loot_acolyte",
    xpReward: 90,
    creditReward: [20, 40],
    aiBehavior: "smart",
  },
  {
    id: "klor_slug_queen",
    name: "Reina Babosa k'lor",
    description: "Un horror hinchado del tamaño de un deslizador de carga. Los túneles profundos resuenan con el chasquido de su prole.",
    level: 4,
    category: "boss",
    primary: { strength: 9, agility: 2, endurance: 11, force: 0, influence: 0, corruption: 1 },
    baseHp: 380,
    baseFp: 0,
    armor: 45,
    resistances: { poison: 1.0 },
    skillIds: ["enemy_bite", "enemy_plague_spit", "enemy_stomp", "enemy_web"],
    lootTableId: "loot_beast",
    xpReward: 180,
    creditReward: [30, 70],
    aiBehavior: "aggressive",
  },
  {
    id: "tukata_alpha",
    name: "Tuk'ata Alfa",
    description: "El líder de la manada — el doble de grande que los suyos, la melena erizada de energía del lado oscuro. Ha aprendido a cazar acólitos.",
    level: 4,
    category: "elite",
    primary: { strength: 9, agility: 7, endurance: 7, force: 3, influence: 0, corruption: 2 },
    baseHp: 240,
    baseFp: 20,
    armor: 35,
    resistances: { force: 0.25 },
    skillIds: ["enemy_bite", "enemy_pounce", "enemy_pack_howl", "enemy_bleed_slash"],
    lootTableId: "loot_beast",
    xpReward: 120,
    creditReward: [10, 25],
    aiBehavior: "smart",
  },
  {
    id: "hssiss",
    name: "Hssiss",
    description: "Un dragón del lado oscuro de las tumbas profundas. Su veneno corroe el espíritu con la misma certeza que la carne.",
    level: 6,
    category: "elite",
    primary: { strength: 9, agility: 6, endurance: 8, force: 5, influence: 0, corruption: 5 },
    baseHp: 260,
    baseFp: 40,
    armor: 45,
    resistances: { poison: 0.6, force: 0.2 },
    skillIds: ["enemy_lightning_bite", "enemy_poison_spit", "enemy_claw_swipe", "enemy_charge"],
    lootTableId: "loot_beast",
    xpReward: 140,
    creditReward: [5, 25],
    aiBehavior: "aggressive",
  },
  {
    id: "terentatek",
    name: "Terentatek",
    description: "El horror de las tumbas que se alimenta de sangre sensible a la Fuerza. Hasta los Lores Sith hablan de él en susurros. A pocos de los que encuentran uno se les cree — menos aún sobreviven.",
    level: 8,
    category: "boss",
    primary: { strength: 14, agility: 4, endurance: 13, force: 2, influence: 0, corruption: 8 },
    baseHp: 950,
    baseFp: 0,
    armor: 70,
    resistances: { force: 0.6, mental: 0.8, poison: 1.0 },
    skillIds: ["enemy_claw_swipe", "enemy_bleed_slash", "enemy_slam", "enemy_charge", "enemy_enrage"],
    lootTableId: "loot_boss_guardian",
    xpReward: 450,
    creditReward: [50, 120],
    aiBehavior: "aggressive",
  },
  {
    id: "mine_overseer",
    name: "Supervisor Drex",
    description: "El capataz de esclavos de la mina. Su látigo de descargas ha acabado con más vidas que los propios túneles.",
    level: 4,
    category: "elite",
    primary: { strength: 7, agility: 5, endurance: 7, force: 2, influence: 4, corruption: 3 },
    baseHp: 210,
    baseFp: 20,
    armor: 40,
    resistances: {},
    skillIds: ["enemy_stun_baton", "enemy_vibroblade", "enemy_call_reinforcements"],
    lootTableId: "loot_elite_sith",
    xpReward: 110,
    creditReward: [30, 60],
    aiBehavior: "smart",
  },
  {
    id: "smuggler_raider",
    name: "Saqueador de Tumbas",
    description: "Un contrabandista de otro mundo que desvalija las tumbas en busca de artefactos. Rápido con el bláster, más rápido huyendo.",
    level: 4,
    category: "minion",
    primary: { strength: 5, agility: 7, endurance: 4, force: 0, influence: 2, corruption: 0 },
    baseHp: 110,
    baseFp: 0,
    armor: 25,
    resistances: {},
    skillIds: ["enemy_blaster", "enemy_grenade", "enemy_knife_stab"],
    lootTableId: "loot_acolyte",
    xpReward: 50,
    creditReward: [25, 60],
    aiBehavior: "random",
  },
  {
    id: "thane_deserter",
    name: "Thane",
    description: "Un acólito fracasado al que no le queda nada que perder. La desesperación hace peligroso hasta al débil.",
    level: 2,
    category: "minion",
    primary: { strength: 5, agility: 5, endurance: 4, force: 3, influence: 2, corruption: 1 },
    baseHp: 95,
    baseFp: 25,
    armor: 15,
    resistances: {},
    skillIds: ["enemy_knife_stab", "enemy_force_push"],
    lootTableId: "loot_acolyte",
    xpReward: 40,
    creditReward: [10, 30],
    aiBehavior: "random",
  },
];

KORRIBAN_ENEMIES.push(...KORRIBAN_EXPANSION_ENEMIES);

/** Quick lookup map. */
export const ENEMY_MAP = new Map(KORRIBAN_ENEMIES.map((e) => [e.id, e]));

// ─── Dungeon Boss: Spirit of Ragnos ────────────────────────────────────

export const DUNGEON_BOSSES: EnemyTemplate[] = [
  {
    id: "ragnos_spirit",
    name: "Espíritu de Marka Ragnos",
    description: "La forma espectral del antiguo Lord Sith Marka Ragnos. Su poder trasciende la muerte.",
    level: 10,
    category: "boss",
    primary: { strength: 12, agility: 8, endurance: 10, force: 14, influence: 12, corruption: 10 },
    baseHp: 1000,
    baseFp: 200,
    armor: 40,
    resistances: { physical: 0.5, energy: 0.3, force: -0.2, mental: 0.6 },
    skillIds: ["enemy_force_lightning", "enemy_force_drain", "enemy_dark_heal", "enemy_fear_aura", "enemy_ancient_beam"],
    lootTableId: "loot_dungeon_ragnos",
    xpReward: 600,
    creditReward: [200, 400],
    aiBehavior: "smart",
  },
];
