import type { EnemyTemplate } from "./enemies";

/**
 * Enemies for all planets beyond Korriban.
 * Source: Master Design Bible §6 + zone hotspot references.
 */

// ═══════════════════════════════════════════════════════════════════════
// NAR SHADDAA (Levels 11-18)
// ═══════════════════════════════════════════════════════════════════════

export const NAR_SHADDAA_ENEMIES: EnemyTemplate[] = [
  {
    id: "street_thug",
    name: "Matón callejero",
    description: "Escoria de baja estofa de la Luna de los Contrabandistas. Desesperados y armados con blásters robados.",
    level: 11,
    category: "minion",
    primary: { strength: 7, agility: 8, endurance: 6, force: 0, influence: 2, corruption: 1 },
    baseHp: 180,
    baseFp: 0,
    armor: 25,
    resistances: {},
    skillIds: ["enemy_blaster", "enemy_knife_stab"],
    lootTableId: "loot_thug",
    xpReward: 60,
    creditReward: [15, 35],
    aiBehavior: "aggressive",
  },
  {
    id: "bounty_hunter",
    name: "Cazarrecompensas",
    description: "Cazador profesional que rastrea objetivos en Nar Shaddaa. Bien equipado e ingenioso.",
    level: 13,
    category: "minion",
    primary: { strength: 8, agility: 10, endurance: 7, force: 0, influence: 4, corruption: 2 },
    baseHp: 250,
    baseFp: 0,
    armor: 45,
    resistances: { energy: 0.1 },
    skillIds: ["enemy_blaster", "enemy_grenade", "enemy_grapple"],
    lootTableId: "loot_hunter",
    xpReward: 90,
    creditReward: [30, 60],
    aiBehavior: "smart",
  },
  {
    id: "exchange_enforcer",
    name: "Ejecutor del Intercambio",
    description: "Músculo del sindicato criminal del Intercambio. Fuertemente armado y leal a los créditos.",
    level: 12,
    category: "minion",
    primary: { strength: 10, agility: 6, endurance: 9, force: 0, influence: 3, corruption: 3 },
    baseHp: 280,
    baseFp: 0,
    armor: 55,
    resistances: {},
    skillIds: ["enemy_heavy_blaster", "enemy_stun_baton"],
    lootTableId: "loot_enforcer",
    xpReward: 75,
    creditReward: [25, 50],
    aiBehavior: "aggressive",
  },
  {
    id: "rakghoul",
    name: "Rakghoul",
    description: "Seres mutados que acechan en la Ciudad Baja. Su mordedura porta la plaga rakghoul.",
    level: 12,
    category: "minion",
    primary: { strength: 9, agility: 7, endurance: 8, force: 0, influence: 0, corruption: 5 },
    baseHp: 200,
    baseFp: 0,
    armor: 20,
    resistances: { poison: 0.8, mental: 0.5 },
    skillIds: ["enemy_bite", "enemy_claw_swipe", "enemy_plague_spit"],
    lootTableId: "loot_beast",
    xpReward: 70,
    creditReward: [0, 10],
    aiBehavior: "aggressive",
  },
  {
    id: "exchange_boss",
    name: "El Jefe del Intercambio",
    description: "Señor del crimen de los bajos fondos de Nar Shaddaa. Rodeado de guardaespaldas y tecnología peligrosa.",
    level: 16,
    category: "boss",
    primary: { strength: 12, agility: 9, endurance: 11, force: 3, influence: 12, corruption: 6 },
    baseHp: 1200,
    baseFp: 40,
    armor: 70,
    resistances: { mental: 0.3 },
    skillIds: ["enemy_heavy_blaster", "enemy_grenade", "enemy_call_reinforcements", "enemy_shield_generator"],
    lootTableId: "loot_boss_exchange",
    xpReward: 600,
    creditReward: [300, 600],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// ONDERON (Levels 15-22)
// ═══════════════════════════════════════════════════════════════════════

export const ONDERON_ENEMIES: EnemyTemplate[] = [
  {
    id: "boma_beast",
    name: "Bestia boma",
    description: "Gran depredador nativo de Onderon y Dxun. Poderoso ataque de embestida.",
    level: 15,
    category: "minion",
    primary: { strength: 12, agility: 6, endurance: 11, force: 0, influence: 0, corruption: 0 },
    baseHp: 320,
    baseFp: 0,
    armor: 40,
    resistances: { physical: 0.1 },
    skillIds: ["enemy_charge", "enemy_bite", "enemy_stomp"],
    lootTableId: "loot_beast",
    xpReward: 110,
    creditReward: [0, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "drexl_larva",
    name: "Larva de drexl",
    description: "Drexl juvenil. Ya del tamaño de un deslizador y muy agresivo.",
    level: 17,
    category: "minion",
    primary: { strength: 14, agility: 5, endurance: 13, force: 0, influence: 0, corruption: 0 },
    baseHp: 400,
    baseFp: 0,
    armor: 55,
    resistances: { physical: 0.15, energy: 0.1 },
    skillIds: ["enemy_bite", "enemy_wing_buffet", "enemy_screech"],
    lootTableId: "loot_beast",
    xpReward: 130,
    creditReward: [0, 20],
    aiBehavior: "aggressive",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// DXUN (Levels 18-28)
// ═══════════════════════════════════════════════════════════════════════

export const DXUN_ENEMIES: EnemyTemplate[] = [
  {
    id: "mandalorian_scout",
    name: "Explorador mandaloriano",
    description: "Un guerrero mandaloriano de patrulla. Rápido y letal a distancia.",
    level: 18,
    category: "minion",
    primary: { strength: 10, agility: 12, endurance: 9, force: 0, influence: 5, corruption: 1 },
    baseHp: 350,
    baseFp: 0,
    armor: 55,
    resistances: { energy: 0.15 },
    skillIds: ["enemy_blaster", "enemy_grenade", "enemy_jet_pack_strike"],
    lootTableId: "loot_mando",
    xpReward: 140,
    creditReward: [40, 80],
    aiBehavior: "smart",
  },
  {
    id: "mandalorian_warrior",
    name: "Guerrero mandaloriano",
    description: "Mandaloriano veterano. Armadura pesada, armas pesadas y sin miedo.",
    level: 20,
    category: "elite",
    primary: { strength: 13, agility: 10, endurance: 12, force: 0, influence: 6, corruption: 2 },
    baseHp: 550,
    baseFp: 0,
    armor: 75,
    resistances: { physical: 0.1, energy: 0.2 },
    skillIds: ["enemy_heavy_blaster", "enemy_flamethrower", "enemy_vibroblade", "enemy_rally"],
    lootTableId: "loot_mando",
    xpReward: 200,
    creditReward: [60, 120],
    aiBehavior: "smart",
  },
  {
    id: "cannok",
    name: "Cannok",
    description: "Depredador de manada de Dxun. Pequeños pero numerosos, abruman a sus presas por número.",
    level: 18,
    category: "minion",
    primary: { strength: 8, agility: 11, endurance: 6, force: 0, influence: 0, corruption: 0 },
    baseHp: 200,
    baseFp: 0,
    armor: 15,
    resistances: {},
    skillIds: ["enemy_bite", "enemy_pack_howl"],
    lootTableId: "loot_beast",
    xpReward: 90,
    creditReward: [0, 8],
    aiBehavior: "aggressive",
  },
  {
    id: "tomb_lord_dxun",
    name: "Lord de la Tumba de Dxun",
    description: "Antiguo espíritu sith atado a la tumba de Dxun. Domina la sombra y el fuego.",
    level: 25,
    category: "boss",
    primary: { strength: 14, agility: 8, endurance: 14, force: 16, influence: 10, corruption: 14 },
    baseHp: 1800,
    baseFp: 200,
    armor: 60,
    resistances: { physical: 0.3, force: 0.2, mental: 0.5 },
    skillIds: ["enemy_shadow_strike", "enemy_force_lightning", "enemy_dark_heal", "enemy_raise_dead", "enemy_void_blast"],
    lootTableId: "loot_boss_tomb_lord",
    xpReward: 900,
    creditReward: [200, 400],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// DANTOOINE (Levels 20-30)
// ═══════════════════════════════════════════════════════════════════════

export const DANTOOINE_ENEMIES: EnemyTemplate[] = [
  {
    id: "kath_hound",
    name: "Sabueso kath",
    description: "El depredador emblemático de Dantooine. Cazadores de manada que pululan por las llanuras de cristal.",
    level: 20,
    category: "minion",
    primary: { strength: 11, agility: 10, endurance: 9, force: 0, influence: 0, corruption: 0 },
    baseHp: 350,
    baseFp: 0,
    armor: 30,
    resistances: {},
    skillIds: ["enemy_bite", "enemy_charge", "enemy_pack_howl"],
    lootTableId: "loot_beast",
    xpReward: 130,
    creditReward: [0, 12],
    aiBehavior: "aggressive",
  },
  {
    id: "kinrath",
    name: "Kinrath",
    description: "Criaturas con aspecto de araña que habitan las cuevas de cristal. Venenosas y territoriales.",
    level: 22,
    category: "minion",
    primary: { strength: 10, agility: 12, endurance: 8, force: 0, influence: 0, corruption: 0 },
    baseHp: 300,
    baseFp: 0,
    armor: 25,
    resistances: { poison: 0.6 },
    skillIds: ["enemy_bite", "enemy_poison_spit", "enemy_web"],
    lootTableId: "loot_beast",
    xpReward: 140,
    creditReward: [0, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "mercenary",
    name: "Mercenario",
    description: "Chatarreros y mercenarios que merodean las ruinas. Armados y dispuestos a matar por créditos.",
    level: 21,
    category: "minion",
    primary: { strength: 10, agility: 9, endurance: 9, force: 0, influence: 3, corruption: 2 },
    baseHp: 380,
    baseFp: 0,
    armor: 45,
    resistances: {},
    skillIds: ["enemy_blaster", "enemy_vibroblade", "enemy_grenade"],
    lootTableId: "loot_enforcer",
    xpReward: 150,
    creditReward: [35, 70],
    aiBehavior: "smart",
  },
  {
    id: "corrupted_guardian",
    name: "Guardián corrupto",
    description: "Un constructo guardián Jedi pervertido por el lado oscuro. Reliquia de una Orden caída.",
    level: 26,
    category: "boss",
    primary: { strength: 15, agility: 10, endurance: 15, force: 14, influence: 5, corruption: 10 },
    baseHp: 2000,
    baseFp: 180,
    armor: 80,
    resistances: { force: 0.25, physical: 0.2 },
    skillIds: ["enemy_saber_combo", "enemy_force_push", "enemy_shield_bash", "enemy_dark_heal", "enemy_enrage"],
    lootTableId: "loot_boss_guardian",
    xpReward: 1000,
    creditReward: [150, 300],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// TELOS (Levels 28-38)
// ═══════════════════════════════════════════════════════════════════════

export const TELOS_ENEMIES: EnemyTemplate[] = [
  {
    id: "czerka_merc",
    name: "Mercenario de Czerka",
    description: "Ejecutores corporativos de la Corporación Czerka. Asesinos profesionales con respaldo empresarial.",
    level: 28,
    category: "minion",
    primary: { strength: 12, agility: 11, endurance: 11, force: 0, influence: 4, corruption: 3 },
    baseHp: 500,
    baseFp: 0,
    armor: 60,
    resistances: { energy: 0.15 },
    skillIds: ["enemy_heavy_blaster", "enemy_grenade", "enemy_shield_generator"],
    lootTableId: "loot_enforcer",
    xpReward: 200,
    creditReward: [50, 100],
    aiBehavior: "smart",
  },
  {
    id: "salvage_droid",
    name: "Droide de salvamento",
    description: "Droides de construcción reprogramados. Pesados e implacables.",
    level: 29,
    category: "minion",
    primary: { strength: 14, agility: 4, endurance: 16, force: 0, influence: 0, corruption: 0 },
    baseHp: 600,
    baseFp: 0,
    armor: 80,
    resistances: { mental: 1.0, poison: 1.0, force: 0.3 },
    skillIds: ["enemy_blaster", "enemy_shock", "enemy_slam"],
    lootTableId: "loot_droid",
    xpReward: 180,
    creditReward: [20, 45],
    aiBehavior: "defensive",
  },
  {
    id: "wild_beast",
    name: "Bestia salvaje",
    description: "Fauna mutada en la superficie de Telos en recuperación. Agresiva y territorial.",
    level: 28,
    category: "minion",
    primary: { strength: 13, agility: 9, endurance: 12, force: 0, influence: 0, corruption: 0 },
    baseHp: 450,
    baseFp: 0,
    armor: 35,
    resistances: {},
    skillIds: ["enemy_bite", "enemy_charge", "enemy_claw_swipe"],
    lootTableId: "loot_beast",
    xpReward: 170,
    creditReward: [0, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "rakata_construct",
    name: "Constructo Rakata",
    description: "Antigua tecnología del Imperio Infinito aún operativa. Escudos de energía y rayos de desintegración.",
    level: 35,
    category: "boss",
    primary: { strength: 16, agility: 8, endurance: 18, force: 12, influence: 0, corruption: 8 },
    baseHp: 3000,
    baseFp: 150,
    armor: 100,
    resistances: { physical: 0.25, energy: 0.3, mental: 1.0, poison: 1.0 },
    skillIds: ["enemy_disintegrate", "enemy_shock", "enemy_shield_generator", "enemy_ancient_beam", "enemy_repair"],
    lootTableId: "loot_boss_rakata",
    xpReward: 1500,
    creditReward: [400, 800],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// MALACHOR V (Levels 35-50)
// ═══════════════════════════════════════════════════════════════════════

export const MALACHOR_ENEMIES: EnemyTemplate[] = [
  {
    id: "storm_beast",
    name: "Bestia de tormenta",
    description: "Enormes depredadores nativos de Malachor V. Atraídos por la energía del lado oscuro.",
    level: 35,
    category: "minion",
    primary: { strength: 16, agility: 8, endurance: 15, force: 5, influence: 0, corruption: 8 },
    baseHp: 700,
    baseFp: 0,
    armor: 50,
    resistances: { force: 0.2, shock: 0.5 },
    skillIds: ["enemy_charge", "enemy_stomp", "enemy_screech", "enemy_lightning_bite"],
    lootTableId: "loot_beast",
    xpReward: 300,
    creditReward: [0, 20],
    aiBehavior: "aggressive",
  },
  {
    id: "shadow_assassin",
    name: "Asesino de las sombras",
    description: "Asesinos sith adiestrados en el sigilo y la muerte. Emergen de las sombras sin previo aviso.",
    level: 37,
    category: "elite",
    primary: { strength: 12, agility: 16, endurance: 10, force: 14, influence: 6, corruption: 12 },
    baseHp: 800,
    baseFp: 120,
    armor: 40,
    resistances: { mental: 0.3 },
    skillIds: ["enemy_shadow_strike", "enemy_poison_blade", "enemy_force_cloak", "enemy_backstab"],
    lootTableId: "loot_elite_sith",
    xpReward: 400,
    creditReward: [60, 120],
    aiBehavior: "smart",
  },
  {
    id: "void_wraith",
    name: "Espectro del vacío",
    description: "Entidades espectrales nacidas de la destrucción del Generador de Sombra Másica. Se alimentan de la fuerza vital.",
    level: 38,
    category: "elite",
    primary: { strength: 6, agility: 14, endurance: 8, force: 18, influence: 5, corruption: 16 },
    baseHp: 600,
    baseFp: 200,
    armor: 10,
    resistances: { physical: 0.5, energy: 0.3, force: -0.3 },
    skillIds: ["enemy_force_drain", "enemy_fear_aura", "enemy_void_blast", "enemy_phase_shift"],
    lootTableId: "loot_wraith",
    xpReward: 450,
    creditReward: [0, 30],
    aiBehavior: "smart",
  },
  {
    id: "sith_marauder_elite",
    name: "Merodeador Sith de élite",
    description: "Guerrero adiestrado en Trayus. Sables dobles y furia desatada.",
    level: 40,
    category: "elite",
    primary: { strength: 16, agility: 14, endurance: 13, force: 12, influence: 6, corruption: 14 },
    baseHp: 1000,
    baseFp: 100,
    armor: 55,
    resistances: { force: 0.15 },
    skillIds: ["enemy_saber_combo", "enemy_rage", "enemy_force_scream", "enemy_whirlwind"],
    lootTableId: "loot_elite_sith",
    xpReward: 500,
    creditReward: [80, 160],
    aiBehavior: "aggressive",
  },
  {
    id: "ghost_captain",
    name: "Capitán fantasma",
    description: "El capitán espectral de una nave de guerra de la República. Atrapado entre la vida y la muerte desde el Generador de Sombra Másica.",
    level: 42,
    category: "boss",
    primary: { strength: 10, agility: 12, endurance: 14, force: 18, influence: 12, corruption: 15 },
    baseHp: 3500,
    baseFp: 250,
    armor: 20,
    resistances: { physical: 0.6, energy: 0.4, force: -0.2, mental: 0.5 },
    skillIds: ["enemy_force_drain", "enemy_fear_aura", "enemy_spectral_barrage", "enemy_call_reinforcements", "enemy_void_blast"],
    lootTableId: "loot_boss_ghost",
    xpReward: 2000,
    creditReward: [300, 600],
    aiBehavior: "smart",
  },

  // ─── Triumvirate Bosses ──────────────────────────────────────────────
  {
    id: "darth_sion",
    name: "Darth Sion, Señor del Dolor",
    description: "El Señor del Dolor. Su cuerpo está destrozado, pero lo mantienen unido la pura rabia y el lado oscuro. No puede morir de verdad.",
    level: 45,
    category: "boss",
    primary: { strength: 20, agility: 12, endurance: 22, force: 16, influence: 8, corruption: 18 },
    baseHp: 5000,
    baseFp: 180,
    armor: 90,
    resistances: { physical: 0.2, force: 0.2 },
    skillIds: ["enemy_saber_combo", "enemy_rage", "enemy_force_scream", "enemy_pain_embrace", "enemy_undying"],
    lootTableId: "loot_boss_sion",
    xpReward: 3000,
    creditReward: [500, 1000],
    aiBehavior: "aggressive",
  },
  {
    id: "darth_nihilus",
    name: "Darth Nihilus, Señor del Hambre",
    description: "El Señor del Hambre. Más vacío que hombre. Consume mundos y devora la Fuerza misma.",
    level: 47,
    category: "boss",
    primary: { strength: 8, agility: 10, endurance: 15, force: 25, influence: 15, corruption: 22 },
    baseHp: 4500,
    baseFp: 400,
    armor: 50,
    resistances: { force: 0.4, mental: 0.6, physical: -0.1 },
    skillIds: ["enemy_force_drain", "enemy_void_blast", "enemy_consume", "enemy_force_storm", "enemy_mass_drain"],
    lootTableId: "loot_boss_nihilus",
    xpReward: 4000,
    creditReward: [600, 1200],
    aiBehavior: "smart",
  },
  {
    id: "darth_traya",
    name: "Darth Traya, Señora de la Traición",
    description: "La Señora de la Traición. La forma final de Kreia. Tres sables de luz la orbitan, guiados solo por la Fuerza. La prueba definitiva.",
    level: 50,
    category: "boss",
    primary: { strength: 14, agility: 14, endurance: 16, force: 28, influence: 20, corruption: 20 },
    baseHp: 6000,
    baseFp: 500,
    armor: 70,
    resistances: { force: 0.3, mental: 0.5, physical: 0.15, energy: 0.2 },
    skillIds: [
      "enemy_triple_saber",
      "enemy_force_lightning",
      "enemy_force_drain",
      "enemy_dark_heal",
      "enemy_force_storm",
      "enemy_betrayal_stance",
      "enemy_force_subjugate",
    ],
    lootTableId: "loot_boss_traya",
    xpReward: 5000,
    creditReward: [1000, 2000],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// DROMUND KAAS (Levels 8-12) — Act I.5 bridge
// ═══════════════════════════════════════════════════════════════════════

export const DROMUND_KAAS_ENEMIES: EnemyTemplate[] = [
  {
    id: "imperial_guard",
    name: "Guardia imperial",
    description: "Soldado imperial de armadura negra con vibroespada y bláster. Disciplinado e inquebrantable.",
    level: 9,
    category: "minion",
    primary: { strength: 7, agility: 6, endurance: 8, force: 0, influence: 3, corruption: 2 },
    baseHp: 200,
    baseFp: 0,
    armor: 35,
    resistances: { physical: 0.05 },
    skillIds: ["enemy_blaster", "enemy_slash"],
    lootTableId: "loot_acolyte",
    xpReward: 65,
    creditReward: [15, 30],
    aiBehavior: "aggressive",
  },
  {
    id: "kaas_vine_cat",
    name: "Gato de las lianas",
    description: "Un depredador de la jungla de seis extremidades con colmillos bioluminiscentes. Caza en parejas.",
    level: 9,
    category: "minion",
    primary: { strength: 8, agility: 10, endurance: 5, force: 0, influence: 1, corruption: 0 },
    baseHp: 170,
    baseFp: 0,
    armor: 20,
    resistances: {},
    skillIds: ["enemy_bite", "enemy_pounce"],
    lootTableId: "loot_beast",
    xpReward: 55,
    creditReward: [5, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "kaas_shadow_assassin",
    name: "Sombra imperial",
    description: "Un asesino con armadura negra mate, que se funde con la tormenta de la jungla. Golpea desde el ocultamiento.",
    level: 11,
    category: "elite",
    primary: { strength: 9, agility: 12, endurance: 8, force: 4, influence: 5, corruption: 4 },
    baseHp: 380,
    baseFp: 40,
    armor: 40,
    resistances: { energy: 0.1 },
    skillIds: ["enemy_slash", "enemy_throwing_blade"],
    lootTableId: "loot_elite_sith",
    xpReward: 140,
    creditReward: [40, 80],
    aiBehavior: "smart",
  },
  {
    id: "kaas_temple_voice",
    name: "La Voz Superpuesta",
    description: "Un antiguo espíritu sith atado al Templo Oscuro. Conoce tu nombre. Lo conocía antes de que nacieras.",
    level: 12,
    category: "boss",
    primary: { strength: 11, agility: 9, endurance: 12, force: 16, influence: 8, corruption: 10 },
    baseHp: 1400,
    baseFp: 200,
    armor: 50,
    resistances: { force: 0.25, shock: 0.2, physical: 0.1 },
    skillIds: ["enemy_force_choke", "enemy_force_push", "enemy_dark_curse"],
    lootTableId: "loot_wraith",
    xpReward: 600,
    creditReward: [200, 400],
    aiBehavior: "smart",
  },
  {
    id: "kaas_gundark",
    name: "Gundark de la jungla",
    description: "Músculo y furia de cuatro brazos. Los gundarks de Kaas crecen más que sus primos — las tormentas los crían fieros.",
    level: 10,
    category: "minion",
    primary: { strength: 12, agility: 5, endurance: 10, force: 0, influence: 0, corruption: 0 },
    baseHp: 280,
    baseFp: 0,
    armor: 30,
    resistances: { physical: 0.1 },
    skillIds: ["enemy_claw_swipe", "enemy_slam", "enemy_howl"],
    lootTableId: "loot_beast",
    xpReward: 85,
    creditReward: [5, 20],
    aiBehavior: "aggressive",
  },
  {
    id: "kaas_gundark_alpha",
    name: "Gundark alfa",
    description: "El que se llevó el brazo de Brakk. Piel llena de cicatrices, colmillos rotos y memoria para cada cazador que lo hirió.",
    level: 11,
    category: "elite",
    primary: { strength: 15, agility: 6, endurance: 13, force: 0, influence: 0, corruption: 0 },
    baseHp: 700,
    baseFp: 0,
    armor: 45,
    resistances: { physical: 0.15 },
    skillIds: ["enemy_claw_swipe", "enemy_slam", "enemy_charge", "enemy_enrage"],
    lootTableId: "loot_beast",
    xpReward: 280,
    creditReward: [50, 120],
    aiBehavior: "aggressive",
  },
  {
    id: "mortis_assassin",
    name: "Agente de Mortis",
    description: "La mano de Darth Mortis llega lejos. Sus agentes no lucen ningún emblema — sus hojas envenenadas firman por ellos.",
    level: 10,
    category: "minion",
    primary: { strength: 8, agility: 11, endurance: 7, force: 3, influence: 4, corruption: 5 },
    baseHp: 240,
    baseFp: 30,
    armor: 30,
    resistances: { poison: 0.3 },
    skillIds: ["enemy_backstab", "enemy_poison_blade", "enemy_throwing_blade"],
    lootTableId: "loot_elite_sith",
    xpReward: 95,
    creditReward: [25, 55],
    aiBehavior: "smart",
  },
  {
    id: "temple_sentinel",
    name: "Centinela del Templo",
    description: "Un droide de guerra del viejo Imperio, aún haciendo su guardia tras mil años. Su lealtad sobrevivió a sus creadores.",
    level: 10,
    category: "minion",
    primary: { strength: 10, agility: 4, endurance: 11, force: 0, influence: 0, corruption: 0 },
    baseHp: 300,
    baseFp: 0,
    armor: 60,
    resistances: { poison: 1, mental: 1, energy: -0.1 },
    skillIds: ["enemy_shock", "enemy_slam", "enemy_shield_generator"],
    lootTableId: "loot_droid",
    xpReward: 100,
    creditReward: [20, 45],
    aiBehavior: "defensive",
  },
  {
    id: "sanctum_keeper",
    name: "El Guardián del Sanctasanctórum",
    description: "Un imponente constructo de piedra y relámpago atado, alzado por los constructores del Templo para custodiar lo que no debe salir.",
    level: 12,
    category: "boss",
    primary: { strength: 14, agility: 5, endurance: 15, force: 10, influence: 0, corruption: 6 },
    baseHp: 1600,
    baseFp: 120,
    armor: 80,
    resistances: { shock: 0.5, poison: 1, mental: 1 },
    skillIds: ["enemy_slam", "enemy_ancient_beam", "enemy_force_lightning", "enemy_shield_bash"],
    lootTableId: "loot_boss_guardian",
    xpReward: 700,
    creditReward: [250, 450],
    aiBehavior: "smart",
  },
  {
    id: "sludge_creeper",
    name: "Reptador del fango",
    description: "Una cosa pálida y sin ojos que caza en la Cripta por vibración. Los obreros desaparecidos la alimentaron bien.",
    level: 11,
    category: "minion",
    primary: { strength: 9, agility: 8, endurance: 9, force: 0, influence: 0, corruption: 3 },
    baseHp: 260,
    baseFp: 0,
    armor: 25,
    resistances: { poison: 0.8 },
    skillIds: ["enemy_bite", "enemy_poison_spit", "enemy_web"],
    lootTableId: "loot_beast",
    xpReward: 90,
    creditReward: [0, 15],
    aiBehavior: "aggressive",
  },
  {
    id: "undercroft_horror",
    name: "El Horror de la Cripta",
    description: "Algo que las filtraciones del Templo Oscuro hicieron de un experimento de engendro sith fugado. Anida bajo Kaas City — y sigue creciendo.",
    level: 12,
    category: "boss",
    primary: { strength: 14, agility: 7, endurance: 14, force: 6, influence: 0, corruption: 12 },
    baseHp: 1300,
    baseFp: 60,
    armor: 45,
    resistances: { poison: 1, physical: 0.1 },
    skillIds: ["enemy_claw_swipe", "enemy_bleed_slash", "enemy_poison_spit", "enemy_fear_aura"],
    lootTableId: "loot_boss_guardian",
    xpReward: 650,
    creditReward: [180, 350],
    aiBehavior: "aggressive",
  },
];

/** All non-Korriban enemies combined. */
// ═══════════════════════════════════════════════════════════════════════
// KORRIBAN — extra fauna & revenants (early game, levels 2-3)
// ═══════════════════════════════════════════════════════════════════════

export const KORRIBAN_EXTRA_ENEMIES: EnemyTemplate[] = [
  {
    id: "corrupted_pilgrim",
    name: "Peregrino corrupto",
    description: "Un aspirante a acólito que nunca salió de las tumbas. El lado oscuro lleva su mente como un guante.",
    level: 2,
    category: "minion",
    primary: { strength: 5, agility: 4, endurance: 5, force: 4, influence: 1, corruption: 6 },
    baseHp: 75,
    baseFp: 25,
    armor: 12,
    resistances: { mental: 0.3 },
    skillIds: ["enemy_slash", "enemy_dark_curse"],
    lootTableId: "loot_acolyte",
    xpReward: 22,
    creditReward: [3, 12],
    aiBehavior: "aggressive",
  },
  {
    id: "hssiss_drake",
    name: "Draco hssiss",
    description: "Un dragón-lagarto del lado oscuro cuya mordedura supura veneno de sombra. Atraído por los usuarios de la Fuerza.",
    level: 3,
    category: "minion",
    primary: { strength: 8, agility: 6, endurance: 7, force: 2, influence: 0, corruption: 3 },
    baseHp: 110,
    baseFp: 0,
    armor: 28,
    resistances: { poison: 0.5, force: 0.2 },
    skillIds: ["enemy_bite", "enemy_poison_spit", "enemy_pounce"],
    lootTableId: "loot_beast",
    xpReward: 35,
    creditReward: [0, 10],
    aiBehavior: "aggressive",
  },
  {
    id: "acolyte_duelist",
    name: "Acólito duelista",
    description: "Un rival que ha sobrevivido a una docena de pruebas a filo de hoja. Preciso, paciente, letal.",
    level: 4,
    category: "elite",
    primary: { strength: 7, agility: 8, endurance: 6, force: 5, influence: 3, corruption: 4 },
    baseHp: 140,
    baseFp: 30,
    armor: 22,
    resistances: {},
    skillIds: ["enemy_saber_combo", "enemy_force_push", "enemy_shield_bash"],
    lootTableId: "loot_acolyte",
    xpReward: 48,
    creditReward: [12, 28],
    aiBehavior: "smart",
  },
  {
    id: "dreshdae_smuggler",
    name: "Contrabandista de Dreshdae",
    description: "Un traficante de armas de tres al cuarto que depreda a los acólitos solitarios que dejan la Academia.",
    level: 3,
    category: "minion",
    primary: { strength: 5, agility: 8, endurance: 5, force: 0, influence: 2, corruption: 1 },
    baseHp: 85,
    baseFp: 0,
    armor: 18,
    resistances: {},
    skillIds: ["enemy_blaster", "enemy_knife_stab", "enemy_throwing_blade"],
    lootTableId: "loot_acolyte",
    xpReward: 28,
    creditReward: [8, 20],
    aiBehavior: "aggressive",
  },
  {
    id: "tomb_scavenger",
    name: "Carroñero de tumbas",
    description: "Un desesperado profanador de tumbas de Dreshdae que desvalija las tumbas del Valle en busca de reliquias que vender — y mata a quien lo delate ante los Supervisores.",
    level: 2,
    category: "minion",
    primary: { strength: 5, agility: 7, endurance: 4, force: 0, influence: 2, corruption: 2 },
    baseHp: 70,
    baseFp: 0,
    armor: 14,
    resistances: {},
    skillIds: ["enemy_knife_stab", "enemy_throwing_blade"],
    lootTableId: "loot_acolyte",
    xpReward: 20,
    creditReward: [5, 18],
    aiBehavior: "random",
  },
  // ── Boss: Spirit of Marka Ragnos ──────────────────────────────────
  // Climax of the Tomb of Ragnos dungeon (dungeon_ragnos_sanctum). This id was
  // referenced by the zone but never defined — the fight was unwinnable.
  {
    id: "ragnos_spirit",
    name: "Espíritu de Marka Ragnos",
    description: "La sombra atada del Lord Oscuro cuyas conquistas fundaron la Edad de Oro de los Sith. La muerte solo afiló su odio.",
    level: 10,
    category: "boss",
    primary: { strength: 10, agility: 8, endurance: 14, force: 16, influence: 6, corruption: 12 },
    baseHp: 820,
    baseFp: 120,
    armor: 40,
    resistances: { force: 0.4, mental: 0.6, physical: 0.2, shock: -0.2 },
    skillIds: [
      "enemy_force_storm", "enemy_force_drain", "enemy_dark_curse",
      "enemy_spectral_barrage", "enemy_fear_aura", "enemy_dark_heal",
    ],
    lootTableId: "loot_boss_guardian",
    xpReward: 400,
    creditReward: [150, 300],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// DROMUND KAAS — extra jungle & cult threats (levels 10-12)
// ═══════════════════════════════════════════════════════════════════════

export const DROMUND_KAAS_EXTRA_ENEMIES: EnemyTemplate[] = [
  {
    id: "kaas_storm_beast",
    name: "Bestia de tormenta",
    description: "Un depredador de la jungla que se ha alimentado del relámpago eterno de Dromund Kaas tanto tiempo que su piel crepita con carga almacenada.",
    level: 10,
    category: "minion",
    primary: { strength: 10, agility: 8, endurance: 9, force: 0, influence: 0, corruption: 0 },
    baseHp: 240,
    baseFp: 0,
    armor: 35,
    resistances: { shock: 0.6, energy: 0.2 },
    skillIds: ["enemy_bite", "enemy_claw_swipe", "enemy_pounce"],
    lootTableId: "loot_beast",
    xpReward: 80,
    creditReward: [10, 25],
    aiBehavior: "aggressive",
  },
  {
    id: "kaas_dark_acolyte",
    name: "Acólito oscuro del culto",
    description: "Un devoto de los susurros del Templo Oscuro. Las voces se han comido su nombre, dejando solo hambre y el relámpago.",
    level: 11,
    category: "elite",
    primary: { strength: 7, agility: 8, endurance: 8, force: 12, influence: 3, corruption: 10 },
    baseHp: 300,
    baseFp: 90,
    armor: 28,
    resistances: { shock: 0.3, force: 0.2, mental: 0.4 },
    skillIds: ["enemy_force_lightning", "enemy_dark_curse", "enemy_saber_combo"],
    lootTableId: "loot_elite_sith",
    xpReward: 140,
    creditReward: [30, 70],
    aiBehavior: "smart",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// ONDERON — extra (Voss's quarry warband, level 12)
// ═══════════════════════════════════════════════════════════════════════

export const ONDERON_EXTRA_ENEMIES: EnemyTemplate[] = [
  {
    id: "drexl_chieftain",
    name: "Caudillo jinete de drexl",
    description: "Un señor de la guerra saqueador de bestias que cabalga a la batalla sobre un drexl medio domado. Las patrullas orientales de Onderon han sangrado por él demasiado tiempo.",
    level: 12,
    category: "boss",
    primary: { strength: 13, agility: 9, endurance: 12, force: 0, influence: 4, corruption: 2 },
    baseHp: 620,
    baseFp: 0,
    armor: 50,
    resistances: { physical: 0.15, fire: -0.2 },
    skillIds: ["enemy_charge", "enemy_stomp", "enemy_claw_swipe", "enemy_enrage"],
    lootTableId: "loot_elite_sith",
    xpReward: 320,
    creditReward: [120, 240],
    aiBehavior: "aggressive",
  },
];

// ═══════════════════════════════════════════════════════════════════════
// NAR SHADDAA — extra (Cyra's bounty target, level 12)
// ═══════════════════════════════════════════════════════════════════════

export const NAR_SHADDAA_EXTRA_ENEMIES: EnemyTemplate[] = [
  {
    id: "exchange_accountant",
    name: "Vurl el Malversador",
    description: "Un contable del Intercambio que sisó al jefe equivocado y huyó a los niveles inferiores. Manos blandas, gatillo nervioso y una pequeña fortuna en créditos robados.",
    level: 12,
    category: "elite",
    primary: { strength: 4, agility: 7, endurance: 6, force: 0, influence: 5, corruption: 1 },
    baseHp: 200,
    baseFp: 0,
    armor: 20,
    resistances: {},
    skillIds: ["enemy_blaster", "enemy_knife_stab"],
    lootTableId: "loot_elite_sith",
    xpReward: 160,
    creditReward: [200, 400],
    aiBehavior: "random",
  },
];

export const ALL_PLANET_ENEMIES: EnemyTemplate[] = [
  ...DROMUND_KAAS_ENEMIES,
  ...DROMUND_KAAS_EXTRA_ENEMIES,
  ...ONDERON_EXTRA_ENEMIES,
  ...NAR_SHADDAA_EXTRA_ENEMIES,
  ...NAR_SHADDAA_ENEMIES,
  ...ONDERON_ENEMIES,
  ...DXUN_ENEMIES,
  ...DANTOOINE_ENEMIES,
  ...TELOS_ENEMIES,
  ...MALACHOR_ENEMIES,
  ...KORRIBAN_EXTRA_ENEMIES,
];
